# Generated by Django 5.2.7 on 2025-10-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoesDeliDRF', '0003_remove_menuitem_category_menuitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='JoesDeliDRF.category'),
            preserve_default=False,
        ),
    ]
