# Generated by Django 5.2.7 on 2025-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoesDeliDRF', '0004_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
